### ISSUE TITLE
Plugin is not seen in Mautic 2.12.0 upgrade

### ISSUE THREAD

**Issue by Prodigitude** [thirdset/ThirdSetMauticTimingBundle#11]
Did the update schema by CLI and saw that it forced the update but I still don't see it in the list of plugins and the field does not appear when editing campaign actions.

**Comment by collinkrawll** [comment]
Have you cleared your Mautic cache? Also make sure that you do step 4 from the [instructions](https://github.com/thirdset/ThirdSetMauticTimingBundle#installation). 

It's also been reported that leaving the plugin zip file in your plugins directory breaks Mautic's plugin discovery. If it's in there, please try deleting it.

**Comment by Prodigitude** [comment]
I did do that and the cache was cleared. I was reading the closed issue with 2.11 (but it was after midnight for me) so I tried everything except checking permissions and will try and going over the error logs next. Is it showing up in other 2.12 upgrades?

**Comment by Prodigitude** [comment]
It's not permissions or ownership. My error logs show nothing. So if it shows on other 2.12 updates, I am going to speculate that it might be the environment. I am running on a cPanel VPS and the path to cron is /var/spool/cron/username which is different than vanilla linux. Might that be the problem causing a silent failure? I think my next step might be to look for environmental variables in the code. Any amount of help pointing me in the right direction would be appreciated.

**Comment by collinkrawll** [comment]
I just tested the plugin with Mautic 2.12 and it worked for me. I've updated the README file to reflect that the plugin is compatible with Mautic 2.12 (it previously said 2.11).

The one thing that I ran into was that only a couple (maybe 3) plugins were showing up when I first did the install. To fix, I ran the `php app/console cache:clear` console command and then pressed the "Install/Upgrade Plugins" button (on the Plugins page). At that point all of the plugins  (about 30 of them) showed up (including the Timing plugin).

**Comment by Prodigitude** [comment]
It's still not showing up for me on my server despite all efforts. There was no issue getting the plugin to install in my local development environment. And again, my local environment is not a cPanel. I am not certain if the cPanel is the problem or not but at least I can look at the code in my IDE and see if I can catch anything that might be a conflict.  On a side note, my first impression opening it up is nice code writing!

**Comment by Prodigitude** [comment]
I will go ahead and suggest that you close this as you have verified the plugin will work with 2.12 and clearly my problem is something else that is going on.

I will let you know if I can uncover the specific issue.

**Comment by collinkrawll** [comment]
Hmm, okay. Sorry I couldn't be of more help.

You could try installing some other third party Mautic plugin and see it it works. If it doesn't, you'd know pretty much for sure that it is your environment.

I didn't see you respond to the suggestion of checking that the zip file isn't still in your plugins directory. We've had reports that leaving the zip file in there breaks things.

Yes, please post back here if you get it figured out.

**Comment by Prodigitude** [comment]
I've got a plugin that I have custom written for my client installed on the
server. So I know it will add them. I am going to try a few more tricks
that I have used in the past and I will let you know if I can get it to
read.
